import { useState, useCallback } from "react";
import BookablesList from "./BookablesList";
import BookableDetails from "./BookableDetails";

export default function BookablesView() {
  // This 'bookable' will be passed from Child - `BookableDetails`
  // `bookable` state is generated by `BookableDetails`, but this state will be
  // managed by its parent `BookablesView`
  console.log(`in BookableView====`);
  const [bookable, setBookable] = useState();

  console.log(`bookable is :`);
  console.dir(bookable);

  const updateBookable = useCallback((selected) => {
    if (selected) {
      selected.lastShown = Date.now();
      setBookable(selected);
    }
  }, []);

  console.log(`render BookableView====`);
  return (
    <>
      <main className="bookables-page">
        <BookablesList bookable={bookable} setBookable={updateBookable} />
        <BookableDetails bookable={bookable} />
      </main>
    </>
  );
}
