import { useState } from "react";
import BookablesList from "./BookablesList";
import BookableDetails from "./BookableDetails";

export default function BookablesView() {
  // This 'bookable' will be passed from Child - `BookableDetails`
  // `bookable` state is generated by `BookableDetails`, but this state will be
  // managed by its parent `BookablesView`
  const [bookable, setBookable] = useState();

  function updateBookable(selected) {
    if (selected) {
      selected.lastShown = Date.now();
      setBookable(selected);
    }
  }
  return (
    <>
      <BookablesList bookable={bookable} setBookable={updateBookable} />
      <BookableDetails bookable={bookable} />
    </>
  );
}
